# -*- coding: utf-8 -*-
"""regression_MLT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185y-Mrh1AvikWOWLVvmMgd6lSrsm7g-l

### 1. Impor Library
Mengimpor semua library yang diperlukan untuk analisis data, visualisasi, dan pemodelan.

Import Library
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, OneHotEncoder, StandardScaler
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""### 2. Memuat Data
Membaca dataset dari file CSV dan menampilkan ringkasan informasi kolom.

Data Loading
"""

df = pd.read_csv('ai_impact.csv')
df.info()

"""### 3. Matriks Korelasi
Visualisasi heatmap untuk melihat hubungan antar variabel numerik.
"""

plt.figure(figsize=(8, 6))
correlation_matrix = df.select_dtypes(include=np.number).corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Heatmap Korelasi')
plt.show()

"""### 4. Visualisasi Pairplot
Menampilkan hubungan distribusi antar pasangan variabel numerik secara menyeluruh.
"""

sns.pairplot(df.select_dtypes(include=np.number)
plt.show()

"""### 5. Seleksi Fitur Awal
Menghapus kolom yang tidak relevan dari dataframe.
"""

df = df.drop(['Student_ID', 'Major_Category', 'Primary_Use_Case'], axis=1)
df.head()

"""### 6. Cek Outliers
Identifikasi outliers pada data numerik menggunakan boxplot.
"""

plt.figure(figsize=(14, 10))
for i, column in enumerate(df.select_dtypes(include=[np.number]).columns, 1):
    plt.subplot(3, 4, i)
    sns.boxplot(df[column])
    plt.title(f'Bloxplot of {column}')
plt.tight_layout()
plt.show()

"""### 7. Penanganan Outliers
Membersihkan outliers menggunakan metode IQR.
"""

numeric_df = df.select_dtypes(include=np.number)

Q1 = numeric_df.quantile(0.25)
Q3 = numeric_df.quantile(0.75)
IQR = Q3 - Q1

condition = ~((numeric_df < (Q1 - 1.5 * IQR)) | (numeric_df > (Q3 + 1.5 * IQR))).any(axis=1)
df = df.loc[condition]

"""### 8. Validasi Hasil Pembersihan"""

plt.figure(figsize=(14, 10))
for i, column in enumerate(df.select_dtypes(include=[np.number]).columns, 1):
    plt.subplot(3, 4, i)
    sns.boxplot(df[column])
    plt.title(f'Boxplot of {column}')
plt.tight_layout()
plt.show()

"""### 9. Pembagian Dataset
Memecah data menjadi set pelatihan (train) dan set pengujian (test).
"""

df.info()

X = df.drop('Post_Semester_GPA', axis=1)
Y = df['Post_Semester_GPA']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

"""### 10. Pengelompokan Fitur
Memisahkan kolom berdasarkan tipe data kategorikal dan numerik.
"""

cat_features = X.select_dtypes(include='object')
num_features = X.select_dtypes(include=[np.number])

"""### 11. Standarisasi Data
Menyamakan skala fitur numerik menggunakan StandardScaler.
"""

standar_scaler = StandardScaler()
X_train[num_features.columns] = standar_scaler.fit_transform(X_train[num_features.columns])
X_test[num_features.columns] = standar_scaler.transform(X_test[num_features.columns])

"""### 12. Encoding Kategorikal
Mengonversi fitur teks menjadi angka menggunakan Ordinal Encoding sesuai tingkatan.
"""

feature_ordinal = ['Year_of_Study', 'Prompt_Engineering_Skill', 'Institutional_Policy', 'Burnout_Risk_Level']

year_of_study_sort = ['Freshman', 'Sophomore', 'Junior', 'Senior', 'Graduate']
prompt_engineering_skill_sort = ['Beginner', 'Intermediate', 'Advanced']
institutional_policy_sort = ['Strict_Ban', 'Allowed_With_Citation', 'Actively_Encouraged']
burnout_risk_level_sort = ['Low', 'Medium', 'High']

# ordinal encoding
ordinal_encoder = OrdinalEncoder(categories=[year_of_study_sort, prompt_engineering_skill_sort, institutional_policy_sort, burnout_risk_level_sort])
X_train[feature_ordinal] = ordinal_encoder.fit_transform(X_train[feature_ordinal])
X_test[feature_ordinal] = ordinal_encoder.transform(X_test[feature_ordinal])

"""### 13. Visualisasi Histogram
Menampilkan distribusi frekuensi untuk setiap variabel dalam set pelatihan.
"""

num_vars = df.shape[1]

n_cols = 4
n_rows = -(-num_vars // n_cols)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, n_rows * 4))

axes = axes.flatten()

for i, column in enumerate(X_train[num_features.columns]):
    df[column].hist(ax=axes[i], bins=20, edgecolor='black')
    axes[i].set_title(column)
    axes[i].set_xlabel('Value')
    axes[i].set_ylabel('Frequency')

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""### 14. Korelasi terhadap Target
Melihat seberapa kuat pengaruh setiap variabel terhadap Post_Semester_GPA.
"""

df_corr = pd.concat([X_train, y_train], axis=1)

target_corr = df_corr.corr()['Post_Semester_GPA']
target_corr = target_corr.drop('Post_Semester_GPA')
target_corr_sorted = target_corr.abs().sort_values(ascending=False)

plt.figure(figsize=(7, 4))
target_corr_sorted.plot(kind='bar')
plt.title('Correlation with Post_Semester_GPA')
plt.xlabel('Variables')
plt.ylabel('Absolute Correlation Coefficient')
plt.show()

"""### 15. Cek Dimensi Data
Memastikan jumlah baris dan kolom sudah benar sebelum pemodelan.
"""

print(f"Training set shape: X_train={X_train.shape}, y_train={y_train.shape}")
print(f"Test set shape: X_test={X_test.shape}, y_test={y_test.shape}")

"""### 16. Eksperimen Model
Melatih model Lars, Linear Regression, dan GBR serta menghitung metrik evaluasi.
"""

lars = linear_model.Lars(n_nonzero_coefs=1).fit(X_train, y_train)
LR = LinearRegression().fit(X_train, y_train)
GBR = GradientBoostingRegressor(random_state=184).fit(X_train, y_train)

pred_lars = lars.predict(X_test)
pred_LR = LR.predict(X_test)
pred_GBR = GBR.predict(X_test)


mae_lars = mean_absolute_error(y_test, pred_lars)
mse_lars = mean_squared_error(y_test, pred_lars)
r2_lars = r2_score(y_test, pred_lars)

mae_LR = mean_absolute_error(y_test, pred_LR)
mse_LR = mean_squared_error(y_test, pred_LR)
r2_LR = r2_score(y_test, pred_LR)

mae_GBR = mean_absolute_error(y_test, pred_GBR)
mse_GBR = mean_squared_error(y_test, pred_GBR)
r2_GBR = r2_score(y_test, pred_GBR)

"""### 17. Perbandingan Performa
Menyajikan tabel ringkasan MAE, MSE, dan R2 untuk semua model yang diuji.
"""

data = {
    'MAE': [mae_lars, mae_LR, mae_GBR],
    'MSE': [mse_lars, mse_LR, mse_GBR],
    'R2': [r2_lars, r2_LR, r2_GBR]
}

df_results = pd.DataFrame(data, index=['Lars', 'Linear Regression', 'GBR'])
df_results